name: Lint (Ruff)

on:
  workflow_dispatch:
  pull_request:

jobs:
  ruff:
    name: Lint (Ruff)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          version: 0.5.6
          args: check --config .ruff.toml
